## 1.1.1向量与矩阵

In [1]:
# 向量与矩阵

In [2]:
import numpy as np

In [3]:
x = np.array([1, 2, 3])  # 可以使用 np.array() 方法生成向量或矩阵

In [4]:
x.__class__  # 该方法会生成NumPy 的多维数组类 np.ndarray

numpy.ndarray

In [5]:
x.shape  # shape 表示多维数组的形状

(3,)

In [6]:
x.ndim  # ndim 表示维数

1

In [7]:
W = np.array([[1, 2, 3], [4, 5, 6]])

In [8]:
W.shape

(2, 3)

In [9]:
W.ndim

2

## 1.1.2 矩阵对应元素的运算

In [10]:
W = np.array([[1, 2, 3], [4, 5, 6]])

In [11]:
X = np.array([[0, 1, 2], [3, 4, 5]])

In [12]:
W + X

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [13]:
W * X

array([[ 0,  2,  6],
       [12, 20, 30]])

In [ ]:
"""
这里对 NumPy 多维数组执行了 +、* 等运算。此时，运算是对应多维
数组中的元素（独立）进行的，这就是 NumPy 数组中的对应元素的运算。
"""

## 1.1.3 广播

In [ ]:
"""
在 NumPy 多维数组中，形状不同的数组之间也可以进行运算，比如下面这个计算
"""

In [16]:
A = np.array([[1, 2], [3, 4]])

In [17]:
A * 10

array([[10, 20],
       [30, 40]])

In [ ]:
"""
这个计算是一个 2 × 2 的矩阵 A 乘以标量 10。此时，如图 1-3 所示，标
量 10 先被扩展为 2 × 2 的矩阵(矩阵的值都为10)，之后进行对应元素的运算。这个灵巧的功
能称为广播
"""

In [18]:
b = np.array([10, 20])

In [19]:
A * b

array([[10, 40],
       [30, 80]])

## 1.1.4 向量内积和矩阵乘积

In [ ]:
"""
现在，我们用 Python 实现一下向量内积和矩阵乘积。为此，可以利用
np.dot()。
"""

In [20]:
a = np.array([1, 2, 3])

In [21]:
b = np.array([4, 5, 6])

In [22]:
np.dot(a, b)

32

In [24]:
A = np.array([[1, 2], [3, 4]])

In [25]:
B = np.array([[5, 6], [7, 8]])
np.dot(A, B)

array([[19, 22],
       [43, 50]])