## 1.2.1 神经网络的推理全貌图

In [1]:
import numpy as np

In [2]:
W1 = np.random.randn(2, 4)  # 权重

In [3]:
b1 = np.random.randn(4)  # 偏置

In [4]:
x = np.random.randn(10, 2)  # 输入

In [5]:
h = np.dot(x, W1) + b1

In [6]:
h

array([[ 1.60837087, -3.39057061,  3.09047977,  0.28817937],
       [-0.02378698, -0.65398261,  0.92482973, -0.48319455],
       [ 0.43285858, -0.09577748,  0.65270635, -1.28258006],
       [ 3.4743166 ,  2.32926308, -0.30228468, -5.61540711],
       [-0.63874938,  1.60664981, -0.70662435, -1.71671483],
       [ 2.09413503, -2.2735667 ,  2.45399409, -0.96340204],
       [ 1.245135  , -2.69290823,  2.54972843,  0.04853937],
       [ 1.7897019 ,  0.54391642,  0.51992492, -2.87645427],
       [ 3.16577703, -1.10961195,  1.91223228, -2.72739633],
       [-0.66198494, -1.04229742,  1.04527229,  0.33353949]])

In [7]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [8]:
x = np.random.randn(10, 2)
W1 = np.random.randn(2, 4)
b1 = np.random.randn(4)
W2 = np.random.randn(4, 3)
b2 = np.random.randn(3)

In [9]:
h = np.dot(x, W1) + b1
a = sigmoid(h)
s = np.dot(a, W2) + b2

In [10]:
s

array([[ 1.28112011, -0.93665197, -2.47111098],
       [ 1.17426483, -0.74907712, -2.68382635],
       [ 0.28383105,  1.20548114, -2.99152416],
       [ 0.3314855 ,  1.06450999, -1.83873771],
       [ 0.65463768,  0.07792789, -3.28431687],
       [ 0.87754789,  0.4077345 , -2.36610468],
       [ 1.39352544, -0.86280201, -2.20167306],
       [ 0.99957774, -0.25240902, -2.78039054],
       [ 0.50874131,  0.97548806, -1.34341042],
       [ 1.24436984, -0.83601081, -2.514161  ]])

## 1.2.2 层的类化及正向传播的实现

In [ ]:
"""
因为这里只考虑正向传播，所以我们仅关注代码规范中的以下两点：一
是在层中实现 forward() 方法；二是将参数整理到实例变量 params 中。
"""

In [12]:
class Sigmoid:
    def __init__(self):
        self.params = []

    def forward(self, x):
        return 1 / (1 + np.exp(-x))

In [ ]:
# 全连接层 Affine 层

In [13]:
class Affine:
    def __init__(self, W, b):
        self.params = [W, b]

    def forward(self, x):
        W, b = self.params
        out = np.dot(x, W) + b
        return out

In [17]:
class TwoLayerNet:
    def __init__(self, input_size, hidden_size, output_size):
        I, H, O = input_size, hidden_size, output_size

        # 初始化权重和偏置
        W1 = np.random.randn(I, H)
        b1 = np.random.randn(H)
        W2 = np.random.randn(H, O)
        b2 = np.random.randn(O)

        # 生成层
        self.layers = [
            Affine(W1, b1),
            Sigmoid(),
            Affine(W2, b2)
        ]

        # 将所有的权重整理到列表中
        self.params = []
        for layer in self.layers:
            self.params += layer.params

    def predict(self, x):
        for layer in self.layers:
            x = layer.forward(x)
        return x

In [18]:
x = np.random.randn(10, 2)
model = TwoLayerNet(2, 4, 3)
s = model.predict(x)

In [19]:
s

array([[-0.02108123,  3.41025848,  3.24252151],
       [-0.20665381,  1.14886442,  2.96906862],
       [-0.37793507,  2.7561923 ,  3.46813863],
       [ 0.64097437,  0.80993855,  2.15040147],
       [-0.10141782,  3.25453281,  3.22653282],
       [ 0.10389036,  2.8603612 ,  2.8592935 ],
       [ 0.1487155 ,  1.09256568,  2.46307406],
       [-0.38884052,  3.0932895 ,  3.62255734],
       [-0.30766674,  3.02943601,  3.47347219],
       [ 0.29128692,  3.64944689,  2.91999511]])