## 3.3.1 上下文和目标词

In [9]:
import sys

import numpy as np

sys.path.append('..')
from common.util import preprocess

In [10]:
text = 'You say goodbye and I say hello.'
corpus, word_to_id, id_to_word = preprocess(text)
print(corpus)

[0 1 2 3 4 1 5 6]


In [11]:
print(id_to_word)

{0: 'you', 1: 'say', 2: 'goodbye', 3: 'and', 4: 'i', 5: 'hello', 6: '.'}


In [20]:
#生成上下文和目标词的函数
def create_contexts_target(corpus, window_size=1):
    target = corpus[window_size:-window_size]
    contexts = []

    for idx in range(window_size, len(corpus) - window_size):
        cs = []
        for t in range(-window_size, window_size + 1):
            if t == 0:
                continue
            cs.append(corpus[idx + t])
        contexts.append(cs)

    return np.array(contexts), np.array(target)

In [21]:
contexts, target = create_contexts_target(corpus, window_size=1)

In [22]:
print(contexts)

[[0 2]
 [1 3]
 [2 4]
 [3 1]
 [4 5]
 [1 6]]


In [23]:
print(target)

[1 2 3 4 1 5]


## 3.3.2 转换为one-hot表示

In [24]:
import sys

sys.path.append('..')
from common.util import preprocess, create_contexts_target, convert_one_hot

In [25]:
text = 'You say goodbye and I say hello.'

In [26]:
corpus, word_to_id, id_to_word = preprocess(text)
contexts, target = create_contexts_target(corpus, window_size=1)

In [27]:
vocab_size = len(word_to_id)
target = convert_one_hot(target, vocab_size)
contexts = convert_one_hot(contexts, vocab_size)